queue: example
jobSetId: job-set-1
jobs:
  - namespace: default
    priority: 0
    podSpec:
      metadata:
        name: config-example
        annotations:
          io.armadaproject.spark.config/file-1: |
            # This is an example config file
            spark:
              config:
                option-1: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
                option-2: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
                option-3: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          io.armadaproject.spark.config/file-2: |
            # This is another example config file
              spark:
                config:
                  option-1: BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                  option-2: BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
      priorityClassName: armada-default
      terminationGracePeriodSeconds: 0
      restartPolicy: Never
      containers:
        - name: sleeper
          image: alpine:latest
          command:
            - sh
          args:
            - -c
            - sleep 600000
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
              readOnly: true
          resources:
            limits:
              memory: 128Mi
              cpu: 2
            requests:
              memory: 128Mi
              cpu: 2
      volumes:
      - name: config-volume
        downwardAPI:
          items:
            - path: "file-1"
              fieldRef:
                fieldPath: metadata.annotations['io.armadaproject.spark.config/file-1']
            - path: "file-2"
              fieldRef:
                fieldPath: metadata.annotations['io.armadaproject.spark.config/file-2']
